import { AdminizerRouteMiddleware } from '@nodeknit/app-adminizer';
import { adminizerConfig } from '../../../../config/adminizer';

/**
 * Middleware for GET /settings/global under Adminizer prefix
 */

export const globalSettingsMiddleware: AdminizerRouteMiddleware = {
  route: '/adminizer/settings/global',
  method: 'get',
  handler: (req, res, next) => {
    const isDev = process.env.NODE_ENV !== 'production';
    const prefix = adminizerConfig.routePrefix;

    // Shared Tailwind CSS asset generated by Vite
    const moduleComponentCSS = `${prefix}/modules/button.css`;
    const moduleComponent = isDev
      ? '/modules/GlobalSettings.tsx'
      : `${prefix}/modules/GlobalSettings.js`;

    if (!req.Inertia || typeof req.Inertia.render !== 'function') {
      console.error('[globalSettingsMiddleware] ERROR: Inertia not initialized');
      return next(new Error('Inertia not initialized'));
    }

    return req.Inertia.render({
      component: 'module',
      props: { moduleComponent,  moduleComponentCSS},
    });
  },
}; 